### ISSUE TITLE
Fonts on https://doc.rust-lang.org/book/ do not work

### ISSUE THREAD

**Issue by KillTheMule** [rust-lang/rust-www#977] opened 2017-11-14 19:39 UTC
Please see https://forums.gentoo.org/viewtopic-p-8141260.html?sid=7a9cf8df88d4a4dce2e13db294fc016c#8141260, I have no idea about why or what, but I went with a dependent problem to the gentoo forums, and user mike155  had a look at the site. If you want, I can submit a PR.

**Comment by mike155** [comment] 2017-11-14 21:21
Duplicate of: https://github.com/rust-lang/rust/issues/45974

**Comment by Mark-Simulacrum** [comment] 2017-11-15 00:31
Closing in favor of https://github.com/rust-lang/rust/issues/45974, thanks!

**Closed by Mark-Simulacrum** 2017-11-15 00:31 UTC
