### ISSUE TITLE
Missing error codes

### ISSUE THREAD

**Issue by adelarsq** [rust-lang/rust-www#495] opened 2016-08-28 15:10 UTC
On the page [Rust Compiler Error Index](https://doc.rust-lang.org/error-index.html) error codes that are bigger than E0522 are missing.

**Comment by steveklabnik** [comment] 2016-08-28 16:12
Sorry you've been bouncing around repos; this is fundamentally a lack in the compiler itself, not the website. All errors have codes, but not all errors have longer explanations yet. This ticket is fundamentally a duplicate of https://github.com/rust-lang/rust/issues/32777

Thanks for filing!

**Closed by steveklabnik** 2016-08-28 16:12 UTC

**Comment by adelarsq** [comment] 2016-08-28 16:31
Got it. Thanks @steveklabnik
